workflows:
  test-workflow:
    name: Test Workflow
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Run unit tests with coverage
        script: |
          flutter test --coverage
          genhtml coverage/lcov.info -o coverage/html
      - name: Run integration tests
        script: flutter drive --target=test/performance_test.dart
    artifacts:
      - coverage/**
      - build/**

    cache:
      cache_paths:
        - /root/.pub-cache
        - build
